version: '3'

services:
  backend:
    build:
      context: ./back-end/
      dockerfile: ./dockerfile
    #image: "dmurphy1217/twitter-sentiment-backend"
    ports:
      - "81:80"
      - "4443:443"
    volumes:
      - ./back-end/:/var/www/html
      - ./back-end/development/certs:/etc/apache2/certs
  frontend:
    build:
      context: ./front-end
      dockerfile: ./dockerfile
    #image: "dmurphy1217/twitter-sentiment-frontend"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front-end/:/app 
      - ./front-end/development/certs:/etc/nginx/certs/
    links:
      - "backend:be"
        
volumes:
  front-end:
  back-end:
       

      
    
                 
    
           
